name: Tests and Coverage
on: [push, pull_request]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone Repository"
        uses: actions/checkout@v2
      - name: Run lorax tests in docker
        run: make tests-in-docker
